/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace DefaultNamespace
{
    public class GarageTableUpdate : TypedRecordUpdate<Tuple<GarageTable?, GarageTable?>> { }

    public class GarageTable : IMudTable
    {
        public static readonly TableId TableId = new("", "Garage");

        public bool? isOccupied;

        public static GarageTable? GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var garageTable = new GarageTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "isOccupied":
                        var isOccupiedValue = (bool)value;
                        garageTable.isOccupied = isOccupiedValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? garageTable : null;
        }

        public static IObservable<GarageTableUpdate> OnRecordUpdate()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString() && update.Type == UpdateType.SetField
                )
                .Select(
                    update =>
                        new GarageTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static IObservable<GarageTableUpdate> OnRecordInsert()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString() && update.Type == UpdateType.SetRecord
                )
                .Select(
                    update =>
                        new GarageTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static IObservable<GarageTableUpdate> OnRecordDelete()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString()
                        && update.Type == UpdateType.DeleteRecord
                )
                .Select(
                    update =>
                        new GarageTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static Tuple<GarageTable?, GarageTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            GarageTable? current = null;
            GarageTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new GarageTable
                    {
                        isOccupied = value.Item1.TryGetValue("isOccupied", out var isOccupiedVal)
                            ? (bool)isOccupiedVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new GarageTable { isOccupied = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new GarageTable
                    {
                        isOccupied = value.Item2.TryGetValue("isOccupied", out var isOccupiedVal)
                            ? (bool)isOccupiedVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new GarageTable { isOccupied = null, };
                }
            }

            return new Tuple<GarageTable?, GarageTable?>(current, previous);
        }
    }
}
