/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace DefaultNamespace
{
    public class TenantTableUpdate : TypedRecordUpdate<Tuple<TenantTable?, TenantTable?>> { }

    public class TenantTable : IMudTable
    {
        public static readonly TableId TableId = new("", "Tenant");

        public string? garageAddress;

        public static TenantTable? GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var tenantTable = new TenantTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "garageAddress":
                        var garageAddressValue = (string)value;
                        tenantTable.garageAddress = garageAddressValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? tenantTable : null;
        }

        public static IObservable<TenantTableUpdate> OnRecordUpdate()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString() && update.Type == UpdateType.SetField
                )
                .Select(
                    update =>
                        new TenantTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static IObservable<TenantTableUpdate> OnRecordInsert()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString() && update.Type == UpdateType.SetRecord
                )
                .Select(
                    update =>
                        new TenantTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static IObservable<TenantTableUpdate> OnRecordDelete()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString()
                        && update.Type == UpdateType.DeleteRecord
                )
                .Select(
                    update =>
                        new TenantTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static Tuple<TenantTable?, TenantTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            TenantTable? current = null;
            TenantTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new TenantTable
                    {
                        garageAddress = value.Item1.TryGetValue(
                            "garageAddress",
                            out var garageAddressVal
                        )
                            ? (string)garageAddressVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new TenantTable { garageAddress = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new TenantTable
                    {
                        garageAddress = value.Item2.TryGetValue(
                            "garageAddress",
                            out var garageAddressVal
                        )
                            ? (string)garageAddressVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new TenantTable { garageAddress = null, };
                }
            }

            return new Tuple<TenantTable?, TenantTable?>(current, previous);
        }
    }
}
