// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Garage, GarageTableId } from "./tables/Garage.sol";
import { Tenant, TenantTableId } from "./tables/Tenant.sol";
import { Position, PositionTableId } from "./tables/Position.sol";
import { Cluster, ClusterTableId } from "./tables/Cluster.sol";
